version: '2'

services:
  secrets:
    build: secrets
    network_mode: 'bridge'
    volumes:
      - /secrets
  transporter:
    image: quay.io/compose/transporter:v0.2.0
    network_mode: "bridge"
    logging:
      options:
        max-size: "500k"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    env_file: secrets/development.env
    environment:
      - TRANSPORTER_ENVIRONMENT=development
    extra_hosts:
      - "mongo-0.db.dnt.local:${DOCKER_IP}"
      - "mongo-1.db.dnt.local:${DOCKER_IP}"
      - "mongo-2.db.dnt.local:${DOCKER_IP}"
      - "mongo-3.db.dnt.local:${DOCKER_IP}"
      - "mongo-4.db.dnt.local:${DOCKER_IP}"
    command: transporter test --config api-users.yml api-users.js
